=== joctan-maceda/tecweb/practicas/p14/Untitled.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:tw="http://tecnologiasweb.com.mx"
    targetNamespace="http://tecnologiasweb.com.mx"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified">
    
    <xsd:element name="SpotifyCatalog" type="tw:SpotifyCatalogType"/>
    
    <xsd:complexType name="SpotifyCatalogType">
        <xsd:sequence>
            <xsd:element name="account" type="tw:AccountType"/>
            <xsd:element name="content" type="tw:ContentType"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="AccountType">
        <xsd:sequence>
            <xsd:element name="profiles" type="tw:ProfilesType"/>
        </xsd:sequence>
        <xsd:attribute name="email" type="xsd:string" use="required"/>
    </xsd:complexType>
    
    <xsd:complexType name="ProfilesType">
        <xsd:sequence>
            <xsd:element name="profile" type="tw:ProfileType" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="ProfileType">
        <xsd:attribute name="username" type="xsd:string" use="required"/>
        <xsd:attribute name="language" type="xsd:string" use="required"/>
    </xsd:complexType>
    
    <xsd:complexType name="ContentType">
        <xsd:sequence>
            <xsd:element name="songs" type="tw:GenresType"/>
            <xsd:element name="podcasts" type="tw:GenresType"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="GenresType">
        <xsd:sequence>
            <xsd:element name="genre" type="tw:GenreType" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="GenreType">
        <xsd:sequence>
            <xsd:element name="title" type="tw:TitleType" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>
    
    <xsd:complexType name="TitleType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="duration" type="xsd:string" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    
</xsd:schema>

=== joctan-maceda/tecweb/practicas/p14/spotify_ns.xml
<?xml version="1.0" encoding="UTF-8"?>
<tw:SpotifyCatalog xmlns:tw="http://tecnologiasweb.com.mx"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://tecnologiasweb.com.mx Untitled.xsd">
    <tw:account email="user@example.com">
        <tw:profiles>
            <tw:profile username="John Doe" language="English"/>
            <tw:profile username="Jane Smith" language="Spanish"/>
        </tw:profiles>
    </tw:account>
    <tw:content>
        <tw:songs>
            <tw:genre name="Pop">
                <tw:title duration="03:30">Blinding Lights</tw:title>
                <tw:title duration="04:10">Levitating</tw:title>
            </tw:genre>
            <tw:genre name="Rock">
                <tw:title duration="05:00">Bohemian Rhapsody</tw:title>
                <tw:title duration="06:00">Hotel California</tw:title>
            </tw:genre>
        </tw:songs>
        <tw:podcasts>
            <tw:genre name="Technology">
                <tw:title duration="01:00:00">Tech Talks</tw:title>
                <tw:title duration="01:20:00">AI Revolution</tw:title>
            </tw:genre>
            <tw:genre name="Health">
                <tw:title duration="00:45:00">Wellness 101</tw:title>
                <tw:title duration="00:50:00">Mental Health Matters</tw:title>
            </tw:genre>
        </tw:podcasts>
    </tw:content>
</tw:SpotifyCatalog>
